name: check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.3'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test.coverage

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
